/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ocp.day21_runnable;

import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import yahoofinance.Stock;
import yahoofinance.YahooFinance;

/**
 *
 * @author MB-teacher
 */
public class ExchangeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExchangeJFrame
     */
    public ExchangeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currencyCombo1 = new javax.swing.JComboBox<>();
        exchangeButton = new javax.swing.JButton();
        currencyCombo2 = new javax.swing.JComboBox<>();
        priceLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("我的匯率");

        currencyCombo1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        currencyCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TWD", "JPY", "USD", "CNY", "EUR" }));

        exchangeButton.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        exchangeButton.setForeground(new java.awt.Color(204, 0, 0));
        exchangeButton.setText("換匯");
        exchangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangeButtonActionPerformed(evt);
            }
        });

        currencyCombo2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        currencyCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TWD", "JPY", "USD", "CNY", "EUR" }));
        currencyCombo2.setSelectedIndex(1);

        priceLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(0, 102, 204));
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("00.00");

        timeLabel.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(51, 102, 0));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("yyyy-mm-dd HH:mm:ss");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currencyCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exchangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currencyCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencyCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exchangeButton)
                    .addComponent(currencyCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(priceLabel)
                .addGap(47, 47, 47)
                .addComponent(timeLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exchangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangeButtonActionPerformed
        
        
    }//GEN-LAST:event_exchangeButtonActionPerformed
    
    // 自行撰寫
    class Exchange implements Runnable {
        @Override
        public void run() {
            String currency1 = currencyCombo1.getItemAt(currencyCombo1.getSelectedIndex());
            String currency2 = currencyCombo2.getItemAt(currencyCombo2.getSelectedIndex());
            String symbol = currency1 + currency2 + "=X";
            try {
                Stock stock = YahooFinance.get(symbol);
                BigDecimal price = stock.getQuote().getPrice();
                Date date = stock.getQuote().getLastTradeTime().getTime();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss E");
                // 將資料放到指定 Label 中顯示
                priceLabel.setText(String.format("%.2f", price.doubleValue()));
                timeLabel.setText(sdf.format(date));
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExchangeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExchangeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExchangeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExchangeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> currencyCombo1;
    private javax.swing.JComboBox<String> currencyCombo2;
    private javax.swing.JButton exchangeButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
